name: CI/CD

on:
  push:
    branches:
      - main
      - dev
      - hom
  pull_request:
    branches:
      - main
      - dev
      - hom

jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Run Tests
        run: mvn test

  publish-image:
    name: Build and Push Docker image
    needs: build-and-test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write   # necessário para GHCR

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to registry
        # Para GitHub Container Registry (GHCR):
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          build-args: |
            PROFILE=${{ github.ref_name }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/user-service:${{ github.ref_name }}
            ghcr.io/${{ github.repository_owner }}/user-service:${{ github.sha }}
